### ISSUE TITLE
Customizing the code

### ISSUE THREAD

**Issue by MehranRastegarSani** [ethanweber/sitcoms3D#15]
Hi, Thanks for sharing your project.
Is it possible to use your code for another dataset?
I want to try it for another TV show like Office. 
Can you guide me if it is possible?

**Comment by ethanweber** [comment]
Hey @MehranRastegarSani, it's possible but it won't work out of the box for this. I recommend reading the paper for the steps we took and then processing the data for the Office in a similar way. This will involve getting frames from a location in the Office and then running COLMAP like how we do in this repo. At this point, I'd also recommend trying to get it working in a real-time repo such as [Nerfstudio](https://github.com/nerfstudio-project/nerfstudio) or with Gaussian Splatting, since then you'll have a real-time interactive experience. However, getting it to work with [NeRF-W](https://nerf-w.github.io/) support (where you can ignore moving parts or clutter in the scene) may take some consideration. I hope this helps you get started. Good luck!
